import type { NextConfig } from "next";

/**
 * The site is published to GitHub Pages under a repository subpath, so the
 * build needs a basePath there and none locally.
 *
 * This is resolved in one place and exported, because three things must agree
 * on it: the build, the static server used for previews and tests
 * (scripts/serve-static.mjs), and Playwright's baseURL. When they disagree the
 * export silently requests assets from the wrong prefix.
 *
 * NOTE: Run `node scripts/generate-assets.mjs` once after cloning to generate
 * all SVG assets (avatars, banners, live-event posters, category cards) that
 * the mock-API data layer references under public/images/.
 */
export const BASE_PATH =
  process.env.NEXT_PUBLIC_BASE_PATH ??
  (process.env.GITHUB_ACTIONS === "true" ? "/myhitch-nexus" : "");

// `headers()` is only supported by the Next.js dev server. Static exports
// (output: "export") are served by CDNs or GitHub Pages where caching is
// configured at the hosting layer. We keep the config object for dev only.
const isDev = process.env.NODE_ENV !== "production";

const nextConfig: NextConfig = {
  // Omit `output: "export"` in dev so the headers() API is available.
  // In CI / `npm run build` the env is set to production automatically.
  ...(isDev ? {} : { output: "export" }),
  basePath: BASE_PATH,
  trailingSlash: true,
  reactStrictMode: true,
  // UI-only build: every image is either a local SVG/poster or a generated
  // data-URI gradient from lib/mock-api. No remote image hosts are configured
  // on purpose — see §12 "explicitly out of scope".
  images: {
    unoptimized: true,
    remotePatterns: [],
  },
  // Cache-control headers for static image assets served during `next dev`.
  // Browsers will cache SVGs, PNGs and JPGs for up to 1 year on first hit,
  // eliminating the slow re-fetches and 404 delays that occur when assets
  // have not yet been generated by `node scripts/generate-assets.mjs`.
  headers: async () => [
    {
      // All generated SVG / photo assets under /images/.
      source: "/images/:path*",
      headers: [
        {
          key: "Cache-Control",
          value: "public, max-age=31536000, immutable",
        },
      ],
    },
    {
      // Top-level JPEG assets (e.g. the WhatsApp image in /public).
      source: "/:file*.jpeg",
      headers: [
        {
          key: "Cache-Control",
          value: "public, max-age=86400, stale-while-revalidate=604800",
        },
      ],
    },
  ],
};

export default nextConfig;
